# Generated by Django 3.1.3 on 2020-11-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_userprofile_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('none', 'none'), ('educating', 'educating'), ('working', 'working')], default='none', max_length=9),
        ),
    ]
