# Generated by Django 3.1.3 on 2020-11-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rank',
            field=models.CharField(choices=[('1', 'Freshman'), ('2', 'Middle'), ('3', 'Experienced')], default='1', max_length=11),
        ),
    ]
