# Generated by Django 3.1.3 on 2020-11-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_userprofile_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rank',
            field=models.CharField(choices=[('Freshman', 'Freshman'), ('Middle', 'Middle'), ('Experienced', 'Experienced')], default='Freshman', max_length=11),
        ),
    ]
