# Generated by Django 3.1.3 on 2020-11-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20201124_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_group',
            field=models.CharField(default='usual_user', max_length=255),
        ),
    ]
