# Generated by Django 3.1.3 on 2020-11-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20201120_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='answer_id',
        ),
        migrations.AddField(
            model_name='rating',
            name='answer_id',
            field=models.ManyToManyField(blank=True, to='question.Answer'),
        ),
        migrations.RemoveField(
            model_name='rating',
            name='comment_id',
        ),
        migrations.AddField(
            model_name='rating',
            name='comment_id',
            field=models.ManyToManyField(blank=True, to='question.Comment'),
        ),
        migrations.RemoveField(
            model_name='rating',
            name='question_id',
        ),
        migrations.AddField(
            model_name='rating',
            name='question_id',
            field=models.ManyToManyField(blank=True, to='question.Question'),
        ),
    ]
