# Generated by Django 3.1.3 on 2020-11-20 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20201120_1047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
