# Generated by Django 3.1.3 on 2020-11-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20201126_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='is_dislike',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='is_like',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user_id',
        ),
        migrations.AddField(
            model_name='vote',
            name='action',
            field=models.CharField(default='up', max_length=255),
        ),
    ]
